// Code generated by protoc-gen-go. DO NOT EDIT.
// source: peer/chaincode.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ConfidentialityLevel int32

const (
	ConfidentialityLevel_PUBLIC       ConfidentialityLevel = 0
	ConfidentialityLevel_CONFIDENTIAL ConfidentialityLevel = 1
)

var ConfidentialityLevel_name = map[int32]string{
	0: "PUBLIC",
	1: "CONFIDENTIAL",
}

var ConfidentialityLevel_value = map[string]int32{
	"PUBLIC":       0,
	"CONFIDENTIAL": 1,
}

func (x ConfidentialityLevel) String() string {
	return proto.EnumName(ConfidentialityLevel_name, int32(x))
}

func (ConfidentialityLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{0}
}

type ChaincodeSpec_Type int32

const (
	ChaincodeSpec_UNDEFINED ChaincodeSpec_Type = 0
	ChaincodeSpec_GOLANG    ChaincodeSpec_Type = 1
	ChaincodeSpec_NODE      ChaincodeSpec_Type = 2
	ChaincodeSpec_CAR       ChaincodeSpec_Type = 3
	ChaincodeSpec_JAVA      ChaincodeSpec_Type = 4
)

var ChaincodeSpec_Type_name = map[int32]string{
	0: "UNDEFINED",
	1: "GOLANG",
	2: "NODE",
	3: "CAR",
	4: "JAVA",
}

var ChaincodeSpec_Type_value = map[string]int32{
	"UNDEFINED": 0,
	"GOLANG":    1,
	"NODE":      2,
	"CAR":       3,
	"JAVA":      4,
}

func (x ChaincodeSpec_Type) String() string {
	return proto.EnumName(ChaincodeSpec_Type_name, int32(x))
}

func (ChaincodeSpec_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{2, 0}
}

type ChaincodeDeploymentSpec_ExecutionEnvironment int32

const (
	ChaincodeDeploymentSpec_DOCKER ChaincodeDeploymentSpec_ExecutionEnvironment = 0
	ChaincodeDeploymentSpec_SYSTEM ChaincodeDeploymentSpec_ExecutionEnvironment = 1
)

var ChaincodeDeploymentSpec_ExecutionEnvironment_name = map[int32]string{
	0: "DOCKER",
	1: "SYSTEM",
}

var ChaincodeDeploymentSpec_ExecutionEnvironment_value = map[string]int32{
	"DOCKER": 0,
	"SYSTEM": 1,
}

func (x ChaincodeDeploymentSpec_ExecutionEnvironment) String() string {
	return proto.EnumName(ChaincodeDeploymentSpec_ExecutionEnvironment_name, int32(x))
}

func (ChaincodeDeploymentSpec_ExecutionEnvironment) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{3, 0}
}

type ChaincodeID struct {
	//deploy transaction will use the path
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	//all other requests will use the name (really a hashcode) generated by
	//the deploy transaction
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	//user friendly version name for the chaincode
	Version              string   `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeID) Reset()         { *m = ChaincodeID{} }
func (m *ChaincodeID) String() string { return proto.CompactTextString(m) }
func (*ChaincodeID) ProtoMessage()    {}
func (*ChaincodeID) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{0}
}

func (m *ChaincodeID) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeID.Unmarshal(m, b)
}
func (m *ChaincodeID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeID.Marshal(b, m, deterministic)
}
func (m *ChaincodeID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeID.Merge(m, src)
}
func (m *ChaincodeID) XXX_Size() int {
	return xxx_messageInfo_ChaincodeID.Size(m)
}
func (m *ChaincodeID) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeID.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeID proto.InternalMessageInfo

func (m *ChaincodeID) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChaincodeID) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// Carries the chaincode function and its arguments.
// UnmarshalJSON in transaction.go converts the string-based REST/JSON input to
// the []byte-based current ChaincodeInput structure.
type ChaincodeInput struct {
	Args                 [][]byte          `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	Decorations          map[string][]byte `protobuf:"bytes,2,rep,name=decorations,proto3" json:"decorations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChaincodeInput) Reset()         { *m = ChaincodeInput{} }
func (m *ChaincodeInput) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInput) ProtoMessage()    {}
func (*ChaincodeInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{1}
}

func (m *ChaincodeInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeInput.Unmarshal(m, b)
}
func (m *ChaincodeInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeInput.Marshal(b, m, deterministic)
}
func (m *ChaincodeInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInput.Merge(m, src)
}
func (m *ChaincodeInput) XXX_Size() int {
	return xxx_messageInfo_ChaincodeInput.Size(m)
}
func (m *ChaincodeInput) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInput.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInput proto.InternalMessageInfo

func (m *ChaincodeInput) GetArgs() [][]byte {
	if m != nil {
		return m.Args
	}
	return nil
}

func (m *ChaincodeInput) GetDecorations() map[string][]byte {
	if m != nil {
		return m.Decorations
	}
	return nil
}

// Carries the chaincode specification. This is the actual metadata required for
// defining a chaincode.
type ChaincodeSpec struct {
	Type                 ChaincodeSpec_Type `protobuf:"varint,1,opt,name=type,proto3,enum=protos.ChaincodeSpec_Type" json:"type,omitempty"`
	ChaincodeId          *ChaincodeID       `protobuf:"bytes,2,opt,name=chaincode_id,json=chaincodeId,proto3" json:"chaincode_id,omitempty"`
	Input                *ChaincodeInput    `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	Timeout              int32              `protobuf:"varint,4,opt,name=timeout,proto3" json:"timeout,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ChaincodeSpec) Reset()         { *m = ChaincodeSpec{} }
func (m *ChaincodeSpec) String() string { return proto.CompactTextString(m) }
func (*ChaincodeSpec) ProtoMessage()    {}
func (*ChaincodeSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{2}
}

func (m *ChaincodeSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeSpec.Unmarshal(m, b)
}
func (m *ChaincodeSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeSpec.Marshal(b, m, deterministic)
}
func (m *ChaincodeSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeSpec.Merge(m, src)
}
func (m *ChaincodeSpec) XXX_Size() int {
	return xxx_messageInfo_ChaincodeSpec.Size(m)
}
func (m *ChaincodeSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeSpec proto.InternalMessageInfo

func (m *ChaincodeSpec) GetType() ChaincodeSpec_Type {
	if m != nil {
		return m.Type
	}
	return ChaincodeSpec_UNDEFINED
}

func (m *ChaincodeSpec) GetChaincodeId() *ChaincodeID {
	if m != nil {
		return m.ChaincodeId
	}
	return nil
}

func (m *ChaincodeSpec) GetInput() *ChaincodeInput {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *ChaincodeSpec) GetTimeout() int32 {
	if m != nil {
		return m.Timeout
	}
	return 0
}

// Specify the deployment of a chaincode.
// TODO: Define `codePackage`.
type ChaincodeDeploymentSpec struct {
	ChaincodeSpec        *ChaincodeSpec                               `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec,proto3" json:"chaincode_spec,omitempty"`
	CodePackage          []byte                                       `protobuf:"bytes,3,opt,name=code_package,json=codePackage,proto3" json:"code_package,omitempty"`
	ExecEnv              ChaincodeDeploymentSpec_ExecutionEnvironment `protobuf:"varint,4,opt,name=exec_env,json=execEnv,proto3,enum=protos.ChaincodeDeploymentSpec_ExecutionEnvironment" json:"exec_env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                     `json:"-"`
	XXX_unrecognized     []byte                                       `json:"-"`
	XXX_sizecache        int32                                        `json:"-"`
}

func (m *ChaincodeDeploymentSpec) Reset()         { *m = ChaincodeDeploymentSpec{} }
func (m *ChaincodeDeploymentSpec) String() string { return proto.CompactTextString(m) }
func (*ChaincodeDeploymentSpec) ProtoMessage()    {}
func (*ChaincodeDeploymentSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{3}
}

func (m *ChaincodeDeploymentSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeDeploymentSpec.Unmarshal(m, b)
}
func (m *ChaincodeDeploymentSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeDeploymentSpec.Marshal(b, m, deterministic)
}
func (m *ChaincodeDeploymentSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeDeploymentSpec.Merge(m, src)
}
func (m *ChaincodeDeploymentSpec) XXX_Size() int {
	return xxx_messageInfo_ChaincodeDeploymentSpec.Size(m)
}
func (m *ChaincodeDeploymentSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeDeploymentSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeDeploymentSpec proto.InternalMessageInfo

func (m *ChaincodeDeploymentSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetCodePackage() []byte {
	if m != nil {
		return m.CodePackage
	}
	return nil
}

func (m *ChaincodeDeploymentSpec) GetExecEnv() ChaincodeDeploymentSpec_ExecutionEnvironment {
	if m != nil {
		return m.ExecEnv
	}
	return ChaincodeDeploymentSpec_DOCKER
}

// Carries the chaincode function and its arguments.
type ChaincodeInvocationSpec struct {
	ChaincodeSpec        *ChaincodeSpec `protobuf:"bytes,1,opt,name=chaincode_spec,json=chaincodeSpec,proto3" json:"chaincode_spec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ChaincodeInvocationSpec) Reset()         { *m = ChaincodeInvocationSpec{} }
func (m *ChaincodeInvocationSpec) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInvocationSpec) ProtoMessage()    {}
func (*ChaincodeInvocationSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{4}
}

func (m *ChaincodeInvocationSpec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeInvocationSpec.Unmarshal(m, b)
}
func (m *ChaincodeInvocationSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeInvocationSpec.Marshal(b, m, deterministic)
}
func (m *ChaincodeInvocationSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInvocationSpec.Merge(m, src)
}
func (m *ChaincodeInvocationSpec) XXX_Size() int {
	return xxx_messageInfo_ChaincodeInvocationSpec.Size(m)
}
func (m *ChaincodeInvocationSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInvocationSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInvocationSpec proto.InternalMessageInfo

func (m *ChaincodeInvocationSpec) GetChaincodeSpec() *ChaincodeSpec {
	if m != nil {
		return m.ChaincodeSpec
	}
	return nil
}

// LifecycleEvent is used as the payload of the chaincode event emitted by LSCC
type LifecycleEvent struct {
	ChaincodeName        string   `protobuf:"bytes,1,opt,name=chaincode_name,json=chaincodeName,proto3" json:"chaincode_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifecycleEvent) Reset()         { *m = LifecycleEvent{} }
func (m *LifecycleEvent) String() string { return proto.CompactTextString(m) }
func (*LifecycleEvent) ProtoMessage()    {}
func (*LifecycleEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{5}
}

func (m *LifecycleEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleEvent.Unmarshal(m, b)
}
func (m *LifecycleEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleEvent.Marshal(b, m, deterministic)
}
func (m *LifecycleEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleEvent.Merge(m, src)
}
func (m *LifecycleEvent) XXX_Size() int {
	return xxx_messageInfo_LifecycleEvent.Size(m)
}
func (m *LifecycleEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleEvent.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleEvent proto.InternalMessageInfo

func (m *LifecycleEvent) GetChaincodeName() string {
	if m != nil {
		return m.ChaincodeName
	}
	return ""
}

// ChaincodeInstallPackage stores the necessary information about a chaincode.
type ChaincodeInstallPackage struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Path                 string   `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	CodePackage          []byte   `protobuf:"bytes,3,opt,name=code_package,json=codePackage,proto3" json:"code_package,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChaincodeInstallPackage) Reset()         { *m = ChaincodeInstallPackage{} }
func (m *ChaincodeInstallPackage) String() string { return proto.CompactTextString(m) }
func (*ChaincodeInstallPackage) ProtoMessage()    {}
func (*ChaincodeInstallPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_202814c635ff5fee, []int{6}
}

func (m *ChaincodeInstallPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChaincodeInstallPackage.Unmarshal(m, b)
}
func (m *ChaincodeInstallPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChaincodeInstallPackage.Marshal(b, m, deterministic)
}
func (m *ChaincodeInstallPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChaincodeInstallPackage.Merge(m, src)
}
func (m *ChaincodeInstallPackage) XXX_Size() int {
	return xxx_messageInfo_ChaincodeInstallPackage.Size(m)
}
func (m *ChaincodeInstallPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_ChaincodeInstallPackage.DiscardUnknown(m)
}

var xxx_messageInfo_ChaincodeInstallPackage proto.InternalMessageInfo

func (m *ChaincodeInstallPackage) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ChaincodeInstallPackage) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ChaincodeInstallPackage) GetCodePackage() []byte {
	if m != nil {
		return m.CodePackage
	}
	return nil
}

func init() {
	proto.RegisterEnum("protos.ConfidentialityLevel", ConfidentialityLevel_name, ConfidentialityLevel_value)
	proto.RegisterEnum("protos.ChaincodeSpec_Type", ChaincodeSpec_Type_name, ChaincodeSpec_Type_value)
	proto.RegisterEnum("protos.ChaincodeDeploymentSpec_ExecutionEnvironment", ChaincodeDeploymentSpec_ExecutionEnvironment_name, ChaincodeDeploymentSpec_ExecutionEnvironment_value)
	proto.RegisterType((*ChaincodeID)(nil), "protos.ChaincodeID")
	proto.RegisterType((*ChaincodeInput)(nil), "protos.ChaincodeInput")
	proto.RegisterMapType((map[string][]byte)(nil), "protos.ChaincodeInput.DecorationsEntry")
	proto.RegisterType((*ChaincodeSpec)(nil), "protos.ChaincodeSpec")
	proto.RegisterType((*ChaincodeDeploymentSpec)(nil), "protos.ChaincodeDeploymentSpec")
	proto.RegisterType((*ChaincodeInvocationSpec)(nil), "protos.ChaincodeInvocationSpec")
	proto.RegisterType((*LifecycleEvent)(nil), "protos.LifecycleEvent")
	proto.RegisterType((*ChaincodeInstallPackage)(nil), "protos.ChaincodeInstallPackage")
}

func init() { proto.RegisterFile("peer/chaincode.proto", fileDescriptor_202814c635ff5fee) }

var fileDescriptor_202814c635ff5fee = []byte{
	// 611 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x6d, 0x6f, 0xd3, 0x30,
	0x10, 0xc7, 0x97, 0x26, 0x7b, 0xba, 0x74, 0x55, 0x30, 0x05, 0xa2, 0xbd, 0x2a, 0x91, 0x10, 0x15,
	0x42, 0x41, 0x2a, 0x13, 0x20, 0x84, 0x26, 0x95, 0x26, 0x9b, 0x32, 0x4a, 0x3a, 0x79, 0x1b, 0x12,
	0xaf, 0xaa, 0x90, 0x5c, 0xbb, 0x68, 0xa9, 0x13, 0x25, 0x6e, 0xb4, 0x7c, 0x0c, 0x3e, 0x09, 0x1f,
	0x11, 0x64, 0x67, 0x7d, 0x62, 0x93, 0x78, 0xc1, 0xab, 0x9c, 0xcf, 0xe7, 0xbb, 0xfb, 0xff, 0x7c,
	0x0e, 0xb4, 0x33, 0xc4, 0xfc, 0x4d, 0x78, 0x1d, 0xc4, 0x2c, 0x4c, 0x23, 0xb4, 0xb3, 0x3c, 0xe5,
	0x29, 0xd9, 0x91, 0x9f, 0xc2, 0x1a, 0x81, 0x3e, 0x58, 0x6c, 0x79, 0x0e, 0x21, 0xa0, 0x65, 0x01,
	0xbf, 0x36, 0x95, 0x8e, 0xd2, 0xdd, 0xa7, 0xd2, 0x16, 0x3e, 0x16, 0xcc, 0xd0, 0x6c, 0xd4, 0x3e,
	0x61, 0x13, 0x13, 0x76, 0x4b, 0xcc, 0x8b, 0x38, 0x65, 0xa6, 0x2a, 0xdd, 0x8b, 0xa5, 0xf5, 0x4b,
	0x81, 0xd6, 0x2a, 0x23, 0xcb, 0xe6, 0x5c, 0x24, 0x08, 0xf2, 0x69, 0x61, 0x2a, 0x1d, 0xb5, 0xdb,
	0xa4, 0xd2, 0x26, 0x1e, 0xe8, 0x11, 0x86, 0x69, 0x1e, 0xf0, 0x38, 0x65, 0x85, 0xd9, 0xe8, 0xa8,
	0x5d, 0xbd, 0xf7, 0xb2, 0x6e, 0xae, 0xb0, 0x37, 0x13, 0xd8, 0xce, 0x2a, 0xd2, 0x65, 0x3c, 0xaf,
	0xe8, 0xfa, 0xd9, 0xc3, 0x63, 0x30, 0xfe, 0x0e, 0x20, 0x06, 0xa8, 0x37, 0x58, 0xdd, 0xc9, 0x10,
	0x26, 0x69, 0xc3, 0x76, 0x19, 0x24, 0xf3, 0x5a, 0x46, 0x93, 0xd6, 0x8b, 0x8f, 0x8d, 0x0f, 0x8a,
	0xf5, 0x5b, 0x81, 0x83, 0x65, 0xc1, 0x8b, 0x0c, 0x43, 0x62, 0x83, 0xc6, 0xab, 0x0c, 0xe5, 0xf1,
	0x56, 0xef, 0xf0, 0x5e, 0x57, 0x22, 0xc8, 0xbe, 0xac, 0x32, 0xa4, 0x32, 0x8e, 0xbc, 0x83, 0xe6,
	0x92, 0xef, 0x38, 0x8e, 0x64, 0x09, 0xbd, 0xf7, 0xf8, 0xbe, 0x1a, 0x87, 0xea, 0xcb, 0x40, 0x2f,
	0x22, 0xaf, 0x61, 0x3b, 0x16, 0x02, 0x25, 0x43, 0xbd, 0xf7, 0xf4, 0x61, 0xf9, 0xb4, 0x0e, 0x12,
	0xcc, 0x79, 0x3c, 0xc3, 0x74, 0xce, 0x4d, 0xad, 0xa3, 0x74, 0xb7, 0xe9, 0x62, 0x69, 0x1d, 0x83,
	0x26, 0xba, 0x21, 0x07, 0xb0, 0x7f, 0xe5, 0x3b, 0xee, 0x89, 0xe7, 0xbb, 0x8e, 0xb1, 0x45, 0x00,
	0x76, 0x4e, 0x47, 0xc3, 0xbe, 0x7f, 0x6a, 0x28, 0x64, 0x0f, 0x34, 0x7f, 0xe4, 0xb8, 0x46, 0x83,
	0xec, 0x82, 0x3a, 0xe8, 0x53, 0x43, 0x15, 0xae, 0xb3, 0xfe, 0xb7, 0xbe, 0xa1, 0x59, 0x3f, 0x1b,
	0xf0, 0x6c, 0x59, 0xd3, 0xc1, 0x2c, 0x49, 0xab, 0x19, 0x32, 0x2e, 0x59, 0x7c, 0x82, 0xd6, 0x4a,
	0x5b, 0x91, 0x61, 0x28, 0xa9, 0xe8, 0xbd, 0x27, 0x0f, 0x52, 0xa1, 0x07, 0xe1, 0x06, 0xc9, 0xe7,
	0xd0, 0x94, 0x07, 0xb3, 0x20, 0xbc, 0x09, 0xa6, 0x28, 0x85, 0x36, 0xa9, 0x2e, 0x7c, 0xe7, 0xb5,
	0x8b, 0x8c, 0x60, 0x0f, 0x6f, 0x31, 0x1c, 0x23, 0x2b, 0xa5, 0xae, 0x56, 0xef, 0xe8, 0x5e, 0xea,
	0xcd, 0x9e, 0x6c, 0xf7, 0x16, 0xc3, 0xb9, 0xb8, 0x6d, 0x97, 0x95, 0x71, 0x9e, 0x32, 0xb1, 0x41,
	0x77, 0x45, 0x16, 0x97, 0x95, 0x96, 0x0d, 0xed, 0x87, 0x02, 0x04, 0x0e, 0x67, 0x34, 0xf8, 0xe2,
	0xd2, 0x1a, 0xcd, 0xc5, 0xf7, 0x8b, 0x4b, 0xf7, 0xab, 0xa1, 0x9c, 0x69, 0x7b, 0x0d, 0x43, 0xa5,
	0x2d, 0x9c, 0x4c, 0x30, 0xe4, 0x71, 0x89, 0xe3, 0x28, 0xe0, 0x68, 0x65, 0x6b, 0x48, 0x3c, 0x56,
	0xa6, 0xa1, 0x1c, 0xaf, 0xff, 0x47, 0x72, 0x57, 0xee, 0x51, 0x1c, 0x8d, 0xa7, 0xc8, 0xb0, 0x9e,
	0xda, 0x71, 0x90, 0x4c, 0xad, 0xf7, 0xd0, 0x1a, 0xc6, 0x13, 0x0c, 0xab, 0x30, 0x41, 0xb7, 0x14,
	0x1d, 0xbf, 0x58, 0x2f, 0x24, 0xdf, 0x60, 0x3d, 0xd0, 0xab, 0x8c, 0x7e, 0x30, 0x43, 0x2b, 0xda,
	0x68, 0xb5, 0xe0, 0x41, 0x92, 0x2c, 0xe0, 0x92, 0xb5, 0x49, 0xde, 0xbf, 0x9b, 0xd6, 0xc5, 0x1b,
	0x6f, 0xac, 0xbd, 0xf1, 0x7f, 0xdf, 0xd3, 0xab, 0x23, 0x68, 0x0f, 0x52, 0x36, 0x89, 0x23, 0x64,
	0x3c, 0x0e, 0x92, 0x98, 0x57, 0x43, 0x2c, 0x31, 0x11, 0x28, 0xcf, 0xaf, 0x3e, 0x0f, 0xbd, 0x81,
	0xb1, 0x45, 0x0c, 0x68, 0x0e, 0x46, 0xfe, 0x89, 0xe7, 0xb8, 0xfe, 0xa5, 0xd7, 0x1f, 0x1a, 0xca,
	0x8f, 0xfa, 0x3f, 0xf3, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x20, 0x45, 0x47, 0xed, 0x86,
	0x04, 0x00, 0x00,
}
