// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proposal.proto

package protos

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HeaderType int32

const (
	HeaderType_CHANNEL_CREATE HeaderType = 0
)

var HeaderType_name = map[int32]string{
	0: "CHANNEL_CREATE",
}

var HeaderType_value = map[string]int32{
	"CHANNEL_CREATE": 0,
}

func (x HeaderType) String() string {
	return proto.EnumName(HeaderType_name, int32(x))
}

func (HeaderType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{0}
}

type SignedProposal struct {
	Signature            []byte    `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	Proposal             *Proposal `protobuf:"bytes,2,opt,name=proposal,proto3" json:"proposal,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SignedProposal) Reset()         { *m = SignedProposal{} }
func (m *SignedProposal) String() string { return proto.CompactTextString(m) }
func (*SignedProposal) ProtoMessage()    {}
func (*SignedProposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{0}
}

func (m *SignedProposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignedProposal.Unmarshal(m, b)
}
func (m *SignedProposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignedProposal.Marshal(b, m, deterministic)
}
func (m *SignedProposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignedProposal.Merge(m, src)
}
func (m *SignedProposal) XXX_Size() int {
	return xxx_messageInfo_SignedProposal.Size(m)
}
func (m *SignedProposal) XXX_DiscardUnknown() {
	xxx_messageInfo_SignedProposal.DiscardUnknown(m)
}

var xxx_messageInfo_SignedProposal proto.InternalMessageInfo

func (m *SignedProposal) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func (m *SignedProposal) GetProposal() *Proposal {
	if m != nil {
		return m.Proposal
	}
	return nil
}

type Proposal struct {
	Header               *Header  `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Payload              []byte   `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Proposal) Reset()         { *m = Proposal{} }
func (m *Proposal) String() string { return proto.CompactTextString(m) }
func (*Proposal) ProtoMessage()    {}
func (*Proposal) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{1}
}

func (m *Proposal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Proposal.Unmarshal(m, b)
}
func (m *Proposal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Proposal.Marshal(b, m, deterministic)
}
func (m *Proposal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Proposal.Merge(m, src)
}
func (m *Proposal) XXX_Size() int {
	return xxx_messageInfo_Proposal.Size(m)
}
func (m *Proposal) XXX_DiscardUnknown() {
	xxx_messageInfo_Proposal.DiscardUnknown(m)
}

var xxx_messageInfo_Proposal proto.InternalMessageInfo

func (m *Proposal) GetHeader() *Header {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Proposal) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Header struct {
	Type                 HeaderType `protobuf:"varint,1,opt,name=type,proto3,enum=protos.HeaderType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_c3ac5ce23bf32d05, []int{2}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetType() HeaderType {
	if m != nil {
		return m.Type
	}
	return HeaderType_CHANNEL_CREATE
}

func init() {
	proto.RegisterEnum("protos.HeaderType", HeaderType_name, HeaderType_value)
	proto.RegisterType((*SignedProposal)(nil), "protos.SignedProposal")
	proto.RegisterType((*Proposal)(nil), "protos.Proposal")
	proto.RegisterType((*Header)(nil), "protos.Header")
}

func init() { proto.RegisterFile("proposal.proto", fileDescriptor_c3ac5ce23bf32d05) }

var fileDescriptor_c3ac5ce23bf32d05 = []byte{
	// 205 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x28, 0xca, 0x2f,
	0xc8, 0x2f, 0x4e, 0xcc, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x03, 0x53, 0xc5, 0x4a,
	0x31, 0x5c, 0x7c, 0xc1, 0x99, 0xe9, 0x79, 0xa9, 0x29, 0x01, 0x50, 0x79, 0x21, 0x19, 0x2e, 0xce,
	0xe2, 0xcc, 0xf4, 0xbc, 0xc4, 0x92, 0xd2, 0xa2, 0x54, 0x09, 0x46, 0x05, 0x46, 0x0d, 0x9e, 0x20,
	0x84, 0x80, 0x90, 0x0e, 0x17, 0x07, 0xcc, 0x24, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x6e, 0x23, 0x01,
	0x88, 0x89, 0xc5, 0x7a, 0x30, 0x13, 0x82, 0xe0, 0x2a, 0x94, 0x7c, 0xb8, 0x38, 0xe0, 0xe6, 0xaa,
	0x71, 0xb1, 0x65, 0xa4, 0x26, 0xa6, 0xa4, 0x16, 0x81, 0x0d, 0xe5, 0x36, 0xe2, 0x83, 0xe9, 0xf3,
	0x00, 0x8b, 0x06, 0x41, 0x65, 0x85, 0x24, 0xb8, 0xd8, 0x0b, 0x12, 0x2b, 0x73, 0xf2, 0x13, 0x53,
	0xc0, 0x16, 0xf0, 0x04, 0xc1, 0xb8, 0x4a, 0x06, 0x5c, 0x6c, 0x10, 0xb5, 0x42, 0x6a, 0x5c, 0x2c,
	0x25, 0x95, 0x05, 0x10, 0xe7, 0xf1, 0x19, 0x09, 0xa1, 0x9a, 0x14, 0x52, 0x59, 0x90, 0x1a, 0x04,
	0x96, 0xd7, 0x52, 0xe0, 0xe2, 0x42, 0x88, 0x09, 0x09, 0x71, 0xf1, 0x39, 0x7b, 0x38, 0xfa, 0xf9,
	0xb9, 0xfa, 0xc4, 0x3b, 0x07, 0xb9, 0x3a, 0x86, 0xb8, 0x0a, 0x30, 0x24, 0x41, 0xc2, 0xc1, 0x18,
	0x10, 0x00, 0x00, 0xff, 0xff, 0xb8, 0x2f, 0xc3, 0x5a, 0x20, 0x01, 0x00, 0x00,
}
